<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
							http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.buskuru.tokyu</groupId>
	<artifactId>buskuru</artifactId>
	<version>SNAPSHOT</version>
	<packaging>apk</packaging>
	<name>BusKuru</name>
	<dependencies>
    	<dependency>
        	<groupId>android</groupId>
        	<artifactId>android</artifactId>
        	<version>4.2.2_r3</version>
        	<scope>provided</scope>
		</dependency>
		<dependency>
    		<groupId>net.sourceforge.htmlcleaner</groupId>
    		<artifactId>htmlcleaner</artifactId>
    		<version>2.6.1</version>
		</dependency>
		<dependency>
            <groupId>com.google.android.gms</groupId>
            <artifactId>google-play-services</artifactId>
            <version>16</version>
            <type>apklib</type>
        </dependency>
        <dependency>
            <groupId>com.google.android.gms</groupId>
            <artifactId>google-play-services</artifactId>
            <version>16</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>android.support</groupId>
            <artifactId>compatibility-v4</artifactId>
            <version>19.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.android.analytics</groupId>
            <artifactId>analytics</artifactId>
            <version>3.0.1</version>
            <type>jar</type>
        </dependency>
		<dependency>
    		<groupId>com.j256.ormlite</groupId>
    		<artifactId>ormlite-core</artifactId>
    		<version>4.48</version>
		</dependency>
		<dependency>
    		<groupId>com.j256.ormlite</groupId>
    		<artifactId>ormlite-android</artifactId>
    		<version>4.48</version>
		</dependency>
    </dependencies>
	<build>
<!-- 		<pluginManagement> -->
<!-- 			<plugins> -->
<!-- 				<plugin> -->
<!-- 					<groupId>com.jayway.maven.plugins.android.generation2</groupId> -->
<!-- 					<artifactId>android-maven-plugin</artifactId> -->
<!-- 					<version>3.9.0-rc.2</version> -->
<!-- 					<configuration> -->
<!-- 						<sdk> -->
<!-- 							<platform>17</platform> -->
<!-- 							<path>C:\Users\satoshi\android-sdks\platforms\android-17</path> -->
<!-- 						</sdk> -->
<!-- 					</configuration> -->
<!-- 					<extensions>true</extensions> -->
<!-- 				</plugin> -->
<!-- 			</plugins> -->
<!-- 		</pluginManagement> -->
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<groupId>com.jayway.maven.plugins.android.generation2</groupId>
				<artifactId>android-maven-plugin</artifactId>
				<version>3.9.0-rc.3</version>
				<configuration>
					<sdk>
						<platform>22</platform>
						<path>${ANDROID_HOME}</path>
					</sdk>
				</configuration>

				<extensions>true</extensions>
			</plugin>
			<plugin>
			    <groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>
		</plugins>
	</build>

<!-- 	<repositories> -->
<!-- 	    <repository> -->
<!-- 	        <id>mvnrepository</id> -->
<!-- 	        <url>http://mvnrepository.com/artifact/</url> -->
<!-- 	    </repository> -->
<!-- 	</repositories> -->

	<repositories>
		<repository>
			<id>bobtabo-station</id>
			<url>http://bobtabo-buhibuhi.synology.me/m2/</url>
		</repository>
		<repository>
			<id>Central Repository</id>
			<url>http://central.maven.org/maven2/</url>
		</repository>
	</repositories>
	<pluginRepositories>
<!-- 		<pluginRepository> -->
<!-- 	        <id>mvnrepository</id> -->
<!-- 	        <url>http://mvnrepository.com/artifact/</url> -->
<!-- 		</pluginRepository> -->
<!-- 		<pluginRepository> -->
<!-- 	        <id>jayway-snapshots</id> -->
<!-- 	        <url>http://oss.sonatype.org/content/repositories/jayway/</url> -->
<!-- 		</pluginRepository> -->
		<pluginRepository>
			<id>bobtabo-station</id>
			<url>http://bobtabo-buhibuhi.synology.me/m2/</url>
		</pluginRepository>
		<pluginRepository>
			<id>Central Repository</id>
			<url>http://central.maven.org/maven2/</url>
		</pluginRepository>
	</pluginRepositories>

	<profiles>
        <profile>
            <id>sign</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jarsigner-plugin</artifactId>
                        <version>1.2</version>
                        <executions>
                            <execution>
                                <id>signing</id>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                                <phase>package</phase>
                                <inherited>true</inherited>
                                <configuration>
                                    <archiveDirectory></archiveDirectory>
                                    <includes>
                                        <include>target/*.apk</include>
                                    </includes>
                                    <keystore>sign/bobtabo.android.keystore</keystore>
                                    <storepass>buhibuhi</storepass>
                                    <keypass>buhibuhi</keypass>
                                    <alias>BobTaboAndroid</alias>
									<arguments>
										<argument>-sigalg</argument>
										<argument>MD5withRSA</argument>
										<argument>-digestalg</argument>
										<argument>SHA1</argument>
									</arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>com.jayway.maven.plugins.android.generation2</groupId>
						<artifactId>android-maven-plugin</artifactId>
                        <inherited>true</inherited>
                        <configuration>
                            <sign>
                                <debug>false</debug>
                            </sign>
                        </configuration>
                    </plugin>
        			<plugin>
          				<groupId>org.codehaus.mojo</groupId>
          				<artifactId>exec-maven-plugin</artifactId>
          				<version>1.4.0</version>
          				<executions>
            				<execution>
              					<id>zipalign</id>
              					<goals>
                					<goal>exec</goal>
              					</goals>
              					<phase>package</phase>
              					<configuration>
                					<executable>${ANDROID_HOME}/build-tools/22.0.1/zipalign</executable>
                						<arguments>
                						    <argument>-f</argument>
                  							<argument>-v</argument>
                  							<argument>4</argument>
                  							<argument>target/${project.build.finalName}.apk</argument>
                  							<argument>target/${project.build.finalName}-zipped.apk</argument>
                						</arguments>
              					</configuration>
            				</execution>
          				</executions>
        			</plugin>
      			</plugins>
    		</build>
        </profile>
    </profiles>
</project>